# Generated by Django 4.2.2 on 2023-06-15 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('converter', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exchangerate',
            name='rate',
            field=models.FloatField(),
        ),
    ]
